---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/apartments":
    get:
      summary: list apartments
      responses:
        '200':
          description: successful
    post:
      summary: create apartment
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                image:
                  type: string
                interior:
                  type: array
                  items:
                    type: string
                maintenance_fee:
                  type: number
                monthly_rent:
                  type: number
                city:
                  type: string
                reservation_expiry_date:
                  type: string
                  format: datetime
              required:
              - name
              - description
              - image
              - interior
              - maintenance_fee
              - monthly_rent
              - city
              - reservation_expiry_date
  "/apartments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show apartment
      responses:
        '200':
          description: successful
    patch:
      summary: update apartment
      responses:
        '200':
          description: successful
    put:
      summary: update apartment
      responses:
        '200':
          description: successful
    delete:
      summary: delete apartment
      responses:
        '200':
          description: successful
  "/user/{user_id}/leases":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list leases
      responses:
        '200':
          description: successful
    post:
      summary: create lease
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  format: datetime
                to:
                  type: string
                  format: datetime
                cancelled:
                  type: boolean
                user_id:
                  type: number
                apartment_id:
                  type: number
              required:
              - from
              - to
              - cancelled
              - user_id
              - apartment_id
  "/user/{user_id}/leases/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show lease
      responses:
        '200':
          description: successful
    patch:
      summary: update lease
      responses:
        '200':
          description: successful
    put:
      summary: update lease
      responses:
        '200':
          description: successful
    delete:
      summary: delete lease
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: lease-a-home-api.herokuapp.com
